package definition

import (
	"github.com/volatiletech/sqlboiler/v4/drivers"
)

type (
	Table struct {
		PageID  string
		Name    string
		Columns []Column
	}

	Column struct {
		RowID         string
		Name          string
		DBType        string
		Unique        bool
		Nullable      bool
		AutoGenerated bool
		PK            bool
		Default       string
		Comment       string
		FreeText      string
	}
)

func ConvertCol(c drivers.Column, tablePK *drivers.PrimaryKey) Column {
	isPK := false
	if tablePK != nil {
		for _, p := range tablePK.Columns {
			if p == c.Name {
				isPK = true
				break
			}
		}
	}

	return Column{
		Name:          c.Name,
		DBType:        c.DBType,
		Unique:        c.Unique,
		Nullable:      c.Nullable,
		PK:            isPK,
		AutoGenerated: c.AutoGenerated,
		Default:       c.Default,
		Comment:       c.Comment,
	}
}
