version: '3'
services:
  postgres:
    container_name: scheman-postgres
    image: postgres:13.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./testdata/postgres:/docker-entrypoint-initdb.d
      - ./tmp/postgresql-data:/var/lib/postgres/data:z
  mysql:
    container_name: scheman-mysql
    platform: linux/x86_64
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./testdata/mysql:/docker-entrypoint-initdb.d
      - ./tmp/mysql-data:/var/lib/mysql/data:z
      
  # @TODO
  # Microsoft 😡

  # mssql:
  #   container_name: mssql
  #   image: :2019-latest
  #   ports:
  #     - 1433:1433
