attr-ignore = ["Auto Generate",]

[psql]
  dbname  = "scheman"
  host    = "localhost"
  port    = 5432
  user    = "root"
  pass    = "password"
  sslmode = "disable"
  schema  = "public"
  blacklist = ["multi_pks"]

[mssql]
  dbname = "scheman"
  host = "localhost"
  port = 1433
  user = "SA"
  pass = "paSsword!001"
