package notion

import (
	"context"

	gn "github.com/dstotijn/go-notion"
	"github.com/maru44/scheman/definition"
)

type (
	columnProps struct {
		// title
		ColumnName gn.DatabasePageProperty `json:"Column Name"`
		// select
		DataType gn.DatabasePageProperty `json:"Data Type"`
		// rich_text
		Default gn.DatabasePageProperty `json:"Default,omitempty"`
		// checkbox
		PK gn.DatabasePageProperty `json:"PK"`
		// checkbox
		AutoGen gn.DatabasePageProperty `json:"Auto Generate"`
		// checkbox
		Unique gn.DatabasePageProperty `json:"Unique"`
		// checkbox
		Nullable gn.DatabasePageProperty `json:"Null"`
		// comment
		Comment gn.DatabasePageProperty `json:"Comment,omitempty"`
		// rich_text
		FreeText gn.DatabasePageProperty `json:"Free Entry,omitempty"`
	}
)

func (n *Notion) createDefRow(ctx context.Context, tableID string, column definition.Column) error {
	if _, err := n.cli.CreatePage(ctx, gn.CreatePageParams{
		ParentType:             gn.ParentTypeDatabase,
		ParentID:               tableID,
		DatabasePageProperties: notionDBPropsFromDriversTable(column),
	}); err != nil {
		return err
	}
	return nil
}

func (n *Notion) updateDefRow(ctx context.Context, column definition.Column) error {
	if _, err := n.cli.UpdatePage(ctx, column.RowID, gn.UpdatePageParams{
		DatabasePageProperties: notionDBPropsFromDriversTable(column),
	}); err != nil {
		return err
	}
	return nil
}

func notionDBPropsFromDriversTable(col definition.Column) *gn.DatabasePageProperties {
	props := &columnProps{
		ColumnName: gn.DatabasePageProperty{
			Title: []gn.RichText{
				{
					Text: &gn.Text{
						Content: col.Name,
					},
				},
			},
		},
		DataType: gn.DatabasePageProperty{
			Select: &gn.SelectOptions{
				Name: col.DBType,
			},
		},
		PK: gn.DatabasePageProperty{
			Checkbox: gn.BoolPtr(col.PK),
		},
		AutoGen: gn.DatabasePageProperty{
			Checkbox: gn.BoolPtr(col.AutoGenerated),
		},
		Unique: gn.DatabasePageProperty{
			Checkbox: gn.BoolPtr(col.Unique),
		},
		Nullable: gn.DatabasePageProperty{
			Checkbox: gn.BoolPtr(col.Nullable),
		},
	}

	dbProps := &gn.DatabasePageProperties{
		"Column Name":   props.ColumnName,
		"Data Type":     props.DataType,
		"PK":            props.PK,
		"Unique":        props.Unique,
		"Null":          props.Nullable,
		"Auto Generate": props.AutoGen,
	}

	if col.Default != "" {
		(*dbProps)["Default"] = gn.DatabasePageProperty{
			RichText: []gn.RichText{
				{
					Text: &gn.Text{
						Content: col.Default,
					},
				},
			},
		}
	}
	if col.Comment != "" {
		(*dbProps)["Comment"] = gn.DatabasePageProperty{
			RichText: []gn.RichText{
				{
					Text: &gn.Text{
						Content: col.Comment,
					},
				},
			},
		}
	}
	if col.FreeText != "" {
		(*dbProps)["Free Entry"] = gn.DatabasePageProperty{
			RichText: []gn.RichText{
				{
					Text: &gn.Text{
						Content: col.FreeText,
					},
				},
			},
		}
	}

	return dbProps
}
